"""
Risk Metric Analysis for European Vanilla Option
Generated by Risk Metric Analyzer Skill
"""
from datetime import datetime
from asset.equity.product.option import EuropeanVanillaOption
from asset.equity.engine.analytical import BlackScholesEngine
from asset.equity.riskmeasures import GreeksCalculator
from util.enum import OptionType
from param import SpotQuote, FlatVolSurface, FlatRateCurve, ContinuousDividendYield
from priceenv import PricingEnvironment
import pandas as pd
import numpy as np
import os

# === Product Configuration ===
STRIKE = 100.0
MATURITY = 1.0  # years
SPOT = 100.0
VOLATILITY = 0.20  # 20%
RATE = 0.05  # 5%
DIV_YIELD = 0.02  # 2%
VALUATION_DATE = datetime(2025, 12, 30)

# === Pricing Environment ===
pricing_env = PricingEnvironment(
    spot_quote=SpotQuote(spot=SPOT),
    vol_surface=FlatVolSurface(volatility=VOLATILITY),
    rate_curve=FlatRateCurve(rate=RATE),
    div_yield=ContinuousDividendYield(div_yield=DIV_YIELD),
    valuation_date=VALUATION_DATE,
)

# === Create Products ===
call_option = EuropeanVanillaOption(
    strike=STRIKE,
    option_type=OptionType.CALL,
    maturity=MATURITY
)

put_option = EuropeanVanillaOption(
    strike=STRIKE,
    option_type=OptionType.PUT,
    maturity=MATURITY
)

# === Create Engine ===
engine = BlackScholesEngine()

# === Calculate Greeks (Analytical) ===
calculator = GreeksCalculator()

# Call option Greeks
call_price = engine.price(call_option, pricing_env)
call_greeks = calculator.calculate_analytical_greeks(call_option, pricing_env)

# Put option Greeks
put_price = engine.price(put_option, pricing_env)
put_greeks = calculator.calculate_analytical_greeks(put_option, pricing_env)

# === Calculate Intrinsic and Time Values ===
# Intrinsic value = max(S - K*e^-(r-q)T, 0) for call, max(K*e^-(r-q)T - S, 0) for put
# Using continuous dividend-adjusted forward strike
forward_strike = STRIKE * np.exp(-RATE * MATURITY)
adjusted_spot = SPOT * np.exp(-DIV_YIELD * MATURITY)

call_intrinsic = max(adjusted_spot - forward_strike, 0)
put_intrinsic = max(forward_strike - adjusted_spot, 0)

call_time_value = call_price - call_intrinsic
put_time_value = put_price - put_intrinsic

# === Verify Put-Call Parity ===
# C - P = S*e^(-qT) - K*e^(-rT)
lhs = call_price - put_price
rhs = adjusted_spot - forward_strike
parity_diff = lhs - rhs

# === Output Results ===
results_call = {
    'Product': 'European Call Option',
    'Strike': STRIKE,
    'Maturity (years)': MATURITY,
    'Spot': SPOT,
    'Volatility': VOLATILITY,
    'Rate': RATE,
    'Dividend Yield': DIV_YIELD,
    'Price': call_price,
    'Intrinsic Value': call_intrinsic,
    'Time Value': call_time_value,
    'Delta': call_greeks['delta'],
    'Gamma': call_greeks['gamma'],
    'Vega': call_greeks['vega'],
    'Theta': call_greeks['theta'],
    'Rho': call_greeks['rho'],
}

results_put = {
    'Product': 'European Put Option',
    'Strike': STRIKE,
    'Maturity (years)': MATURITY,
    'Spot': SPOT,
    'Volatility': VOLATILITY,
    'Rate': RATE,
    'Dividend Yield': DIV_YIELD,
    'Price': put_price,
    'Intrinsic Value': put_intrinsic,
    'Time Value': put_time_value,
    'Delta': put_greeks['delta'],
    'Gamma': put_greeks['gamma'],
    'Vega': put_greeks['vega'],
    'Theta': put_greeks['theta'],
    'Rho': put_greeks['rho'],
}

# Get output directory
script_dir = os.path.dirname(os.path.abspath(__file__))
output_dir = os.path.join(os.path.dirname(script_dir), 'data')
os.makedirs(output_dir, exist_ok=True)

# Save to CSV
df_call = pd.DataFrame([results_call])
df_put = pd.DataFrame([results_put])

df_call.to_csv(os.path.join(output_dir, 'european_call_data.csv'), index=False)
df_put.to_csv(os.path.join(output_dir, 'european_put_data.csv'), index=False)

# Combined summary
summary = {
    'Parameter': ['Strike', 'Maturity', 'Spot', 'Volatility', 'Rate', 'Div Yield'],
    'Value': [STRIKE, MATURITY, SPOT, VOLATILITY, RATE, DIV_YIELD]
}
df_summary = pd.DataFrame(summary)
df_summary.to_csv(os.path.join(output_dir, 'product_parameters.csv'), index=False)

# === Print Results ===
print("=" * 60)
print("Risk Metrics for European Vanilla Option")
print("=" * 60)
print(f"\nValuation Date: {VALUATION_DATE.strftime('%Y-%m-%d')}")
print(f"Spot: {SPOT:.2f}, Strike: {STRIKE:.2f}, Maturity: {MATURITY:.2f} years")
print(f"Volatility: {VOLATILITY:.1%}, Rate: {RATE:.1%}, Div Yield: {DIV_YIELD:.1%}")
print("\n" + "-" * 60)
print("CALL OPTION")
print("-" * 60)
for key, value in results_call.items():
    if isinstance(value, float):
        if key in ['Price', 'Intrinsic Value', 'Time Value', 'Vega', 'Theta', 'Rho']:
            print(f"  {key:18s}: ${value:>10.4f}")
        else:
            print(f"  {key:18s}: {value:>10.6f}")
    else:
        print(f"  {key:18s}: {value}")

print("\n" + "-" * 60)
print("PUT OPTION")
print("-" * 60)
for key, value in results_put.items():
    if isinstance(value, float):
        if key in ['Price', 'Intrinsic Value', 'Time Value', 'Vega', 'Theta', 'Rho']:
            print(f"  {key:18s}: ${value:>10.4f}")
        else:
            print(f"  {key:18s}: {value:>10.6f}")
    else:
        print(f"  {key:18s}: {value}")

print("\n" + "-" * 60)
print("PUT-CALL PARITY CHECK")
print("-" * 60)
print(f"  C - P (LHS):           ${lhs:>10.4f}")
print(f"  S*e^(-qT) - K*e^(-rT): ${rhs:>10.4f}")
print(f"  Difference:            ${parity_diff:>10.6f}")
if abs(parity_diff) < 1e-6:
    print("  Status: PUT ✓ (Parity holds)")
else:
    print(f"  Status: PARITY VIOLATION (diff = {parity_diff:.2e})")

print("\n" + "=" * 60)
print(f"Data saved to: {output_dir}/")
print("=" * 60)
