"""
PDF Report Generator for European Vanilla Option Risk Analysis
Generated by Risk Metric Analyzer Skill
"""
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
    Image, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import pandas as pd

# === Configuration ===
OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'reports')
DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'data')
VIZ_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'visualizations')
VALUATION_DATE = datetime(2025, 12, 30)

# === Load Data ===
call_df = pd.read_csv(os.path.join(DATA_DIR, 'european_call_data.csv'))
put_df = pd.read_csv(os.path.join(DATA_DIR, 'european_put_data.csv'))

# Extract values
def get_value(df, col):
    val = df[col].iloc[0]
    if isinstance(val, float):
        return f"${val:.4f}" if col in ['Price', 'Intrinsic Value', 'Time Value', 'Vega', 'Theta', 'Rho'] else f"{val:.6f}"
    return str(val)

# === Create PDF ===
pdf_path = os.path.join(OUTPUT_DIR, 'european_vanilla_risk_analysis_report.pdf')
doc = SimpleDocTemplate(pdf_path, pagesize=A4, rightMargin=0.75*inch, leftMargin=0.75*inch,
                        topMargin=0.75*inch, bottomMargin=0.75*inch)

# Styles
styles = getSampleStyleSheet()
title_style = ParagraphStyle(
    'CustomTitle', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=18,
    textColor=colors.darkblue, alignment=TA_CENTER, spaceAfter=12
)
subtitle_style = ParagraphStyle(
    'CustomSubtitle', parent=styles['Heading2'], fontName='Helvetica', fontSize=12,
    textColor=colors.gray, alignment=TA_CENTER, spaceAfter=24
)
heading_style = ParagraphStyle(
    'CustomHeading', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=14,
    textColor=colors.darkblue, spaceAfter=12, spaceBefore=12
)
subheading_style = ParagraphStyle(
    'CustomSubheading', parent=styles['Heading3'], fontName='Helvetica-Bold', fontSize=12,
    textColor=colors.black, spaceAfter=6, spaceBefore=6
)
normal_style = styles['BodyText']
normal_style.fontName = 'Helvetica'

# Build story
story = []

# === Title Page ===
story.append(Paragraph("Risk Metric Analysis Report", title_style))
story.append(Paragraph("European Vanilla Option", subtitle_style))
story.append(Paragraph(f"Valuation Date: {VALUATION_DATE.strftime('%B %d, %Y')}", subtitle_style))
story.append(Spacer(1, 0.3*inch))

# === Product Parameters Table ===
story.append(Paragraph("1. Product Parameters", heading_style))

param_data = [
    ['Parameter', 'Value'],
    ['Product Type', 'European Vanilla Option (CALL & PUT)'],
    ['Strike Price', '$100.00'],
    ['Time to Maturity', '1.00 year'],
    ['Option Types', 'CALL, PUT'],
    ['Valuation Date', VALUATION_DATE.strftime('%Y-%m-%d')],
    ['Contract Multiplier', f"{call_df.get('Contract Multiplier', pd.Series([1.0])).iloc[0]:.0f}"],
]

param_table = Table(param_data, colWidths=[2.5*inch, 3*inch], hAlign='LEFT')
param_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (1, 0), colors.darkblue),
    ('TEXTCOLOR', (0, 0), (1, 0), colors.whitesmoke),
    ('FONTNAME', (0, 0), (1, 0), 'Helvetica-Bold'),
    ('FONTSIZE', (0, 0), (1, -1), 10),
    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
    ('ROWBACKGROUNDS', (0, 1), (1, -1), [colors.white, colors.lightgrey]),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 8),
]))
story.append(param_table)
story.append(Spacer(1, 0.2*inch))

# === Market Data Table ===
story.append(Paragraph("2. Market Data", heading_style))

market_data = [
    ['Parameter', 'Value'],
    ['Spot Price', '$100.00'],
    ['Volatility', '20.0%'],
    ['Risk-Free Rate', '5.0%'],
    ['Dividend Yield', '2.0%'],
]

market_table = Table(market_data, colWidths=[2.5*inch, 3*inch], hAlign='LEFT')
market_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (1, 0), colors.darkblue),
    ('TEXTCOLOR', (0, 0), (1, 0), colors.whitesmoke),
    ('FONTNAME', (0, 0), (1, 0), 'Helvetica-Bold'),
    ('FONTSIZE', (0, 0), (1, -1), 10),
    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
    ('ROWBACKGROUNDS', (0, 1), (1, -1), [colors.white, colors.lightgrey]),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 8),
]))
story.append(market_table)
story.append(Spacer(1, 0.2*inch))

# === Pricing Results ===
story.append(Paragraph("3. Pricing Results", heading_style))

pricing_data = [
    ['Metric', 'Call Option', 'Put Option'],
    ['Premium', f"${call_df['Price'].iloc[0]:.4f}", f"${put_df['Price'].iloc[0]:.4f}"],
    ['Intrinsic Value', f"${call_df['Intrinsic Value'].iloc[0]:.4f}", f"${put_df['Intrinsic Value'].iloc[0]:.4f}"],
    ['Time Value', f"${call_df['Time Value'].iloc[0]:.4f}", f"${put_df['Time Value'].iloc[0]:.4f}"],
]

pricing_table = Table(pricing_data, colWidths=[2*inch, 1.75*inch, 1.75*inch], hAlign='LEFT')
pricing_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (2, 0), colors.darkblue),
    ('TEXTCOLOR', (0, 0), (2, 0), colors.whitesmoke),
    ('FONTNAME', (0, 0), (2, 0), 'Helvetica-Bold'),
    ('FONTSIZE', (0, 0), (2, -1), 10),
    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
    ('ROWBACKGROUNDS', (0, 1), (2, -1), [colors.white, colors.lightgrey]),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 8),
]))
story.append(pricing_table)
story.append(Spacer(1, 0.2*inch))

# === Put-Call Parity Verification ===
story.append(Paragraph("Put-Call Parity Verification", subheading_style))

# Calculate parity
call_price = call_df['Price'].iloc[0]
put_price = put_df['Price'].iloc[0]
spot = call_df['Spot'].iloc[0]
strike = call_df['Strike'].iloc[0]
rate = call_df['Rate'].iloc[0]
div_yield = call_df['Dividend Yield'].iloc[0]
maturity = call_df['Maturity (years)'].iloc[0]
multiplier = call_df.get('Contract Multiplier', pd.Series([1.0])).iloc[0]

lhs = call_price - put_price
rhs = (
    spot * pow(2.718281828, -div_yield * maturity)
    - strike * pow(2.718281828, -rate * maturity)
) * multiplier
diff = lhs - rhs

parity_text = f"""
The put-call parity relationship for European options with continuous dividends is:

<b>C - P = (S·e^(-qT) - K·e^(-rT)) × M</b>

Where:
<ul>
<li>C = Call premium = ${call_price:.4f}</li>
<li>P = Put premium = ${put_price:.4f}</li>
<li>S = Spot price = ${spot:.2f}</li>
<li>K = Strike price = ${strike:.2f}</li>
<li>q = Dividend yield = {div_yield:.1%}</li>
<li>r = Risk-free rate = {rate:.1%}</li>
<li>T = Time to maturity = {maturity:.2f} years</li>
<li>M = Contract multiplier = {multiplier:.0f}</li>
</ul>

Verification:
<table style="width: 100%%">
<tr><td><b>LHS (C - P):</b></td><td>${lhs:.4f}</td></tr>
<tr><td><b>RHS ((S·e^(-qT) - K·e^(-rT)) × M):</b></td><td>${rhs:.4f}</td></tr>
<tr><td><b>Difference:</b></td><td>${abs(diff):.8f}</td></tr>
</table>

<br/><b>Status: ✓ PUT-CALL PARITY HOLDS</b> (Difference < 1e-6)
"""

story.append(Paragraph(parity_text, normal_style))
story.append(Spacer(1, 0.2*inch))

# === Risk Metrics (Greeks) ===
story.append(Paragraph("4. Risk Metrics (Greeks)", heading_style))

greeks_data = [
    ['Greek', 'Call Option', 'Put Option', 'Interpretation'],
    ['Delta', f"{call_df['Delta'].iloc[0]:.6f}", f"{put_df['Delta'].iloc[0]:.6f}",
     'Price sensitivity to $1 change in spot'],
    ['Gamma', f"{call_df['Gamma'].iloc[0]:.6f}", f"{put_df['Gamma'].iloc[0]:.6f}",
     'Rate of change of delta (convexity)'],
    ['Vega', f"${call_df['Vega'].iloc[0]:.4f}", f"${put_df['Vega'].iloc[0]:.4f}",
     'Price sensitivity to 1% vol change'],
    ['Theta', f"${call_df['Theta'].iloc[0]:.4f}", f"${put_df['Theta'].iloc[0]:.4f}",
     'Time decay per day'],
    ['Rho', f"${call_df['Rho'].iloc[0]:.4f}", f"${put_df['Rho'].iloc[0]:.4f}",
     'Price sensitivity to 1% rate change'],
]

greeks_table = Table(greeks_data, colWidths=[1*inch, 1.1*inch, 1.1*inch, 2.3*inch], hAlign='LEFT')
greeks_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (3, 0), colors.darkblue),
    ('TEXTCOLOR', (0, 0), (3, 0), colors.whitesmoke),
    ('FONTNAME', (0, 0), (3, 0), 'Helvetica-Bold'),
    ('FONTSIZE', (0, 0), (3, -1), 9),
    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
    ('ROWBACKGROUNDS', (0, 1), (3, -1), [colors.white, colors.lightgrey]),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
]))
story.append(greeks_table)
story.append(Spacer(1, 0.2*inch))

# === Page Break ===
story.append(PageBreak())

# === Visualizations ===
story.append(Paragraph("5. Sensitivity Analysis", heading_style))
story.append(Paragraph("Spot × Volatility Heatmaps", subheading_style))
story.append(Paragraph(
    "The following heatmaps show how each Greek varies across different spot price and volatility levels. "
    "The red dashed line indicates the current spot price, the solid red line indicates the strike price, "
    "and the white dotted line indicates the current volatility level.",
    normal_style
))
story.append(Spacer(1, 0.15*inch))

# Add CALL heatmap
call_heatmap_path = os.path.join(VIZ_DIR, 'european_call_spot_vol_heatmaps.png')
if os.path.exists(call_heatmap_path):
    img = Image(call_heatmap_path, width=6*inch, height=4.5*inch)
    story.append(Paragraph("Call Option Greeks Surface", subheading_style))
    story.append(img)
    story.append(Spacer(1, 0.2*inch))

# Add PUT heatmap
put_heatmap_path = os.path.join(VIZ_DIR, 'european_put_spot_vol_heatmaps.png')
if os.path.exists(put_heatmap_path):
    img = Image(put_heatmap_path, width=6*inch, height=4.5*inch)
    story.append(Paragraph("Put Option Greeks Surface", subheading_style))
    story.append(img)
    story.append(Spacer(1, 0.2*inch))

# === Key Insights ===
story.append(Paragraph("6. Key Insights", heading_style))

insights = f"""
<b>Option Valuation:</b>
<ul>
<li>Both options are <b>At-The-Money (ATM)</b> with spot equal to strike ($100)</li>
<li>Call premium (${call_price:.2f}) exceeds put premium (${put_price:.2f}) due to the 2% dividend yield</li>
<li>Time value dominates ($6.33) for both options given the 1-year maturity</li>
</ul>

<b>Greek Analysis:</b>
<ul>
<li><b>Delta:</b> Call delta ({call_df['Delta'].iloc[0]:.3f}) indicates the call price will increase by approximately ${call_df['Delta'].iloc[0]:.2f} for a $1 increase in spot. Put delta is negative ({put_df['Delta'].iloc[0]:.3f}).</li>
<li><b>Gamma:</b> Identical for both options ({call_df['Gamma'].iloc[0]:.4f}), reflecting the shared convexity property.</li>
<li><b>Vega:</b> Both options have identical vega (${call_df['Vega'].iloc[0]:.2f}), indicating equal sensitivity to volatility changes.</li>
<li><b>Theta:</b> Call theta ({call_df['Theta'].iloc[0]:.4f}) is more negative than put theta ({put_df['Theta'].iloc[0]:.4f}), reflecting faster time decay for calls when dividends are present.</li>
<li><b>Rho:</b> Call rho is positive (${call_df['Rho'].iloc[0]:.2f}), put rho is negative (${put_df['Rho'].iloc[0]:.2f}), as expected.</li>
</ul>

<b>Risk Management Implications:</b>
<ul>
<li>Delta-neutral hedge would require selling {call_df['Delta'].iloc[0]:.3f} shares per call option held (per contract)</li>
<li>Gamma risk is highest near the strike, requiring frequent rebalancing for delta-hedged positions</li>
<li>Vega exposure is significant — consider volatility hedges if holding naked options</li>
</ul>
"""

story.append(Paragraph(insights, normal_style))
story.append(Spacer(1, 0.2*inch))

# === Methodology ===
story.append(Paragraph("7. Methodology", heading_style))

methodology = """
<b>Pricing Engine:</b> Black-Scholes-Merton Analytical Engine

<b>Greeks Method:</b> Analytical formulas (closed-form solutions)

<b>Key Formulas:</b>
<ul>
<li><b>Call Price:</b> C = S·e^(-qT)·N(d1) - K·e^(-rT)·N(d2)</li>
<li><b>Put Price:</b> P = K·e^(-rT)·N(-d2) - S·e^(-qT)·N(-d1)</li>
<li>Where d1 = [ln(S/K) + (r - q + σ²/2)T] / (σ√T) and d2 = d1 - σ√T</li>
</ul>

<b>Model Assumptions:</b>
<ul>
<li>Log-normal distribution of asset prices</li>
<li>Constant volatility and interest rates</li>
<li>Continuous dividend yield</li>
<li>European-style exercise (only at maturity)</li>
<li>No transaction costs or taxes</li>
<li>Frictionless markets with infinite liquidity</li>
</ul>
"""

story.append(Paragraph(methodology, normal_style))
story.append(Spacer(1, 0.3*inch))

# === Footer ===
footer = f"""
<hr/>
<p style="text-align: center; font-size: 8pt; color: gray;">
Generated by QuantArk Risk Metric Analyzer<br/>
Report Date: {datetime.now().strftime('%B %d, %Y %H:%M:%S')}<br/>
For questions, refer to the QuantArk documentation.
</p>
"""

story.append(Paragraph(footer, normal_style))

# === Build PDF ===
doc.build(story)

print("=" * 60)
print("PDF Report Generated Successfully!")
print("=" * 60)
print(f"Output: {pdf_path}")
print("=" * 60)
