"""Render the intraday capability matrix document.

    python -m quantark.intraday.publish docs/execution/intraday-capability-matrix.md

CI enforces freshness (``test/intraday/test_capability_matrix_freshness.py``).
"""
from __future__ import annotations

from quantark.intraday.capability import capability_evidence, greek_evidence, render_capability_matrix

_HEADER = """# QuantArk intraday pricing — capability matrix

> GENERATED by `python -m quantark.intraday.publish` from
> `quantark.intraday.capability.INTRADAY_CAPABILITIES` and the packaged Gate C evidence — do not edit by hand.
> CI enforces freshness (`test/intraday/test_capability_matrix_freshness.py`).

A row exists only where the semantics are implemented. `supported`: the route prices the contract with its stated
limits and reports its numerical status per price. `qualified`: every Gate C price cell of the row passed against the
independent reference (profiles uniform, desk and sessions_only; eleven spot offsets on both sides of each barrier) at
the qualified horizon and every longer horizon to the next fixing. Timestamp support below the qualified horizon does
not imply a Greek-accuracy certificate there, and neither does a price certificate: Greek statuses are bound
separately to the demonstrated families below. Requests outside the matrix raise `CapabilityError` naming the intraday
alternatives; an engine subclass does not inherit a row.

"""


def _greek_section() -> str:
    evidence = greek_evidence()
    rows = evidence.get("demonstrated", ())
    lines = ["## Gate C demonstrated Greeks", ""]
    if not rows:
        lines += ["No Greek has a demonstrated bump/refinement limit yet: point finite-difference proxies report "
                  "`unqualified`.", ""]
        return "\n".join(lines)
    lines += [f"Greek evidence: `quantark/intraday/evidence/gate_c_greeks.json` (git {evidence.get('git_sha', 'n/a')}). "
              "Each row is one demonstrated FAMILY and speaks only for it: the same product under different "
              "monitoring, under a variance profile no row names, or at a time to the next fixing outside the swept "
              "window reports `unqualified` with no value. A `point_*` row lets that route report the point measure "
              "`ok` inside its window; a `desk_*` row records that the configured finite move matched the same move "
              "on the reference.", "",
              "| Product | Route | Measure | Monitoring | Profile | Horizon window (s) | Spot offsets | Barriers |",
              "|---|---|---|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r['product']} | {r['route']} | {r['measure']} | {r.get('monitoring', '?')} | "
                     f"{r.get('profile', '?')} | {r['horizon_s']} – {r.get('horizon_max_s', '?')} | "
                     f"{', '.join(r.get('offsets', ()))} | {', '.join(r.get('barriers', ()))} |")
    lines.append("")
    return "\n".join(lines)


def render_document() -> str:
    evidence = capability_evidence()
    provenance = (f"Price evidence: `quantark/intraday/evidence/gate_c_results.json` (git {evidence.get('git_sha', 'n/a')}, "
                  f"{len(evidence.get('cells', ()))} cells).\n\n") if evidence else "Price evidence: none packaged.\n\n"
    return _HEADER + provenance + "## Routes\n\n" + render_capability_matrix() + "\n" + _greek_section()


def main(argv) -> None:
    text = render_document()
    if argv:
        import pathlib

        path = pathlib.Path(argv[0])
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")
    else:
        print(text, end="")


if __name__ == "__main__":
    import sys

    main(sys.argv[1:])
