"""Render the intraday capability matrix document.

    python -m quantark.intraday.publish docs/execution/intraday-capability-matrix.md

CI enforces freshness (``test/intraday/test_capability_matrix_freshness.py``).
"""
from __future__ import annotations

from quantark.intraday.capability import render_capability_matrix

_HEADER = """# QuantArk intraday pricing — capability matrix

> GENERATED by `python -m quantark.intraday.publish` from
> `quantark.intraday.capability.INTRADAY_CAPABILITIES` — do not edit by hand.
> CI enforces freshness (`test/intraday/test_capability_matrix_freshness.py`).

A row exists only where the semantics are implemented. `supported`: the route prices the contract with its stated
limits and reports its numerical diagnostics per price (PDE resolution, MC standard error, theta truncation estimate).
Requests outside the matrix raise `CapabilityError` naming the intraday alternatives; an engine subclass does not
inherit a row.

Numerical accuracy is not a property of a row. It is measured offline by the studies under
`example/modelvalidation/` and banked under `docs/modelvalidation/`; a production release ships an engine only for
the studies that admit its shipped configuration (`docs/modelvalidation/RELEASE_PROCEDURE.md`).

"""


def render_document() -> str:
    return _HEADER + "## Routes\n\n" + render_capability_matrix()


def main(argv) -> None:
    text = render_document()
    if argv:
        import pathlib

        path = pathlib.Path(argv[0])
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")
    else:
        print(text, end="")


if __name__ == "__main__":
    import sys

    main(sys.argv[1:])
