"""Render the intraday capability matrix document.

    python -m quantark.intraday.publish docs/execution/intraday-capability-matrix.md

CI enforces freshness (``test/intraday/test_capability_matrix_freshness.py``).
"""
from __future__ import annotations

from quantark.intraday.capability import capability_evidence, greek_evidence, render_capability_matrix

_HEADER = """# QuantArk intraday pricing — capability matrix

> GENERATED by `python -m quantark.intraday.publish` from
> `quantark.intraday.capability.INTRADAY_CAPABILITIES` and the packaged Gate C evidence — do not edit by hand.
> CI enforces freshness (`test/intraday/test_capability_matrix_freshness.py`).

A row exists only where the semantics are implemented. `supported`: the route prices the contract with its stated
limits and reports its numerical status per price. `qualified`: every Gate C price cell of the row passed against the
independent reference (profiles uniform, desk and sessions_only; eleven spot offsets on both sides of each barrier) at
the qualified horizon and every longer horizon to the next fixing. Timestamp support below the qualified horizon does
not imply a Greek-accuracy certificate there, and neither does a price certificate: Greek statuses are bound
separately to the demonstrated families below. Requests outside the matrix raise `CapabilityError` naming the intraday
alternatives; an engine subclass does not inherit a row.

"""


#: The accuracy knobs a reader recognises; the full configuration of every row is in the evidence file.
_SETTINGS_SHOWN = ("order", "cells_per_sd", "accuracy", "grid", "num_paths", "seed", "method")


def _settings_label(settings: dict) -> str:
    params = dict(settings.get("params") or {}, method=settings.get("method"))
    shown = ", ".join(f"{k}={params[k]}" for k in _SETTINGS_SHOWN if params.get(k) is not None)
    engine = str(settings.get("engine", "?")).rsplit(".", 1)[-1]
    return f"{engine} ({shown})" if shown else engine


def _greek_sources(evidence: dict) -> str:
    """Every measured revision the packaged Greek evidence rests on, with its cell count."""
    sources = evidence.get("sources")
    if not sources:
        return f"git {evidence.get('git_sha', 'n/a')}"
    return "; ".join(f"git {s['git_sha']}, {s['cells']} cells" for s in sources)


def _greek_section() -> str:
    evidence = greek_evidence()
    rows = evidence.get("demonstrated", ())
    lines = ["## Gate C demonstrated Greeks", ""]
    if not rows:
        lines += ["No Greek has a demonstrated bump/refinement limit yet: point finite-difference proxies report "
                  "`unqualified`.", ""]
        return "\n".join(lines)
    lines += [f"Greek evidence: `quantark/intraday/evidence/gate_c_greeks.json` ({_greek_sources(evidence)}). "
              "Each row is one demonstrated CERTIFICATE and speaks only for it: the same product under different "
              "monitoring, under a variance profile no row names, at other engine settings (the column shows the "
              "recognisable knobs; the evidence file holds the full record), with another measure knob, or at a time "
              "to the next fixing outside the window reports `unqualified` with no value. A `point_*` row lets that "
              "route report the point measure `ok` inside its window; a `desk_*` row lets it report a desk move of "
              "prices that are not exact. Numerical certificates additionally match conditional payoff/event/state/"
              "settlement terms, market curves and levels, calendar, and the demonstrated spot envelope. Other "
              "economics remain unqualified (see the module README).",
              "",
              "Analytical barrier/touch point theta is checked per request on admitted exact prices with three "
              "second-order stencil levels. Its result reports a truncation/cancellation error estimate and the "
              "frozen error budget; an unresolved limit reports `unqualified`. It does not require a family row below.",
              "",
              "| Product | Fixture | Route | Measure | Monitoring | Profile | Engine settings | Measure settings | "
              "Horizon window (s) | Spot offsets | Barriers |",
              "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        knobs = ", ".join(f"{k}={v}" for k, v in sorted((r.get("measure_settings") or {}).items())) or "—"
        fixtures = ", ".join(r.get("fixtures") or ()) or "—"
        lines.append(f"| {r['product']} | {fixtures} | {r['route']} | {r['measure']} | {r.get('monitoring', '?')} | "
                     f"{r.get('profile', '?')} | {_settings_label(r.get('settings') or {})} | {knobs} | "
                     f"{r['horizon_s']} – {r.get('horizon_max_s', '?')} | "
                     f"{', '.join(r.get('offsets', ()))} | {', '.join(r.get('barriers', ()))} |")
    lines.append("")
    return "\n".join(lines)


def render_document() -> str:
    evidence = capability_evidence()
    provenance = (f"Price evidence: `quantark/intraday/evidence/gate_c_results.json` (git {evidence.get('git_sha', 'n/a')}, "
                  f"{len(evidence.get('cells', ()))} cells).\n\n") if evidence else "Price evidence: none packaged.\n\n"
    return _HEADER + provenance + "## Routes\n\n" + render_capability_matrix() + "\n" + _greek_section()


def main(argv) -> None:
    text = render_document()
    if argv:
        import pathlib

        path = pathlib.Path(argv[0])
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")
    else:
        print(text, end="")


if __name__ == "__main__":
    import sys

    main(sys.argv[1:])
