"""
Pricing engines for equity derivatives.
"""

from .base_engine import BaseEngine
from .capabilities import (
    EngineCapability,
    SettlementSupport,
    VolDynamicsType,
    get_engine_capability,
    validate_engine_capability,
)
from .analytical import (
    BlackScholesEngine,
    BarrierAnalyticalEngine,
    OneTouchAnalyticalEngine,
    AsianOptionAnalyticalEngine,
    DoubleSharkfinOptionAnalyticalEngine,
    HestonAnalyticalEngine,
)
from .pde_engine import PDEEngine
from .mc import (
    EuropeanMCEngine,
    AmericanOptionMCEngine,
    DCNMCEngine,
    LocalVolDCNMCEngine,
    CoupledCoarseHestonDCNMCEngine,
    HestonDCNMCEngine,
    QEDCNMCEngine,
    coupled_heston_ladder_pair,
    SnowballMCEngine,
    PhoenixMCEngine,
    DigitalOptionMCEngine,
    BarrierOptionMCEngine,
    DoubleSharkfinOptionMCEngine,
    LocalVolMCEngine,
    HestonMCEngine,
    HestonSLVMCEngine,
    LocalVolSnowballMCEngine,
    HestonSnowballMCEngine,
    QESnowballMCEngine,
    HestonSLVSnowballMCEngine,
    HestonSLVQESnowballMCEngine,
    LocalVolPhoenixMCEngine,
    HestonPhoenixMCEngine,
    QEPhoenixMCEngine,
    HestonSLVPhoenixMCEngine,
    HestonSLVQEPhoenixMCEngine,
)
from .pde import (
    BasePDESolver,
    EuropeanPDESolver,
    AmericanPDESolver,
    BarrierPDESolver,
    DoubleBarrierPDESolver,
    OneTouchPDESolver,
    DoubleOneTouchPDESolver,
    KOResetSnowballPDESolver,
    PhoenixPDESolver,
    LocalVolPDESolver,
    HestonPDESolver,
    HestonSLVPDESolver,
    LocalVolSnowballPDESolver,
    HestonSnowballPDESolver,
    HestonSLVSnowballPDESolver,
    LocalVolPhoenixPDESolver,
    HestonPhoenixPDESolver,
    HestonSLVPhoenixPDESolver,
)
from .quad import (
    EuropeanQuadEngine,
    BarrierQuadEngine,
    OneTouchQuadEngine,
    SnowballQuadEngine,
    KOResetSnowballQuadEngine,
    PhoenixQuadEngine,
)

__all__ = [
    # Base
    "BaseEngine",
    "EngineCapability",
    "SettlementSupport",
    "VolDynamicsType",
    "get_engine_capability",
    "validate_engine_capability",
    # Analytical
    "BlackScholesEngine",
    "BarrierAnalyticalEngine",
    "OneTouchAnalyticalEngine",
    "AsianOptionAnalyticalEngine",
    "DoubleSharkfinOptionAnalyticalEngine",
    "HestonAnalyticalEngine",
    # Monte Carlo
    "EuropeanMCEngine",
    "AmericanOptionMCEngine",
    "DCNMCEngine",
    "LocalVolDCNMCEngine",
    "CoupledCoarseHestonDCNMCEngine",
    "HestonDCNMCEngine",
    "QEDCNMCEngine",
    "coupled_heston_ladder_pair",
    "SnowballMCEngine",
    "PhoenixMCEngine",
    "DigitalOptionMCEngine",
    "BarrierOptionMCEngine",
    "DoubleSharkfinOptionMCEngine",
    "LocalVolMCEngine",
    "HestonMCEngine",
    "HestonSLVMCEngine",
    "LocalVolSnowballMCEngine",
    "HestonSnowballMCEngine",
    "QESnowballMCEngine",
    "HestonSLVSnowballMCEngine",
    "HestonSLVQESnowballMCEngine",
    "LocalVolPhoenixMCEngine",
    "HestonPhoenixMCEngine",
    "QEPhoenixMCEngine",
    "HestonSLVPhoenixMCEngine",
    "HestonSLVQEPhoenixMCEngine",
    # Unified PDE Engine
    "PDEEngine",
    # PDE Solvers
    "BasePDESolver",
    "EuropeanPDESolver",
    "AmericanPDESolver",
    "BarrierPDESolver",
    "DoubleBarrierPDESolver",
    "OneTouchPDESolver",
    "DoubleOneTouchPDESolver",
    "KOResetSnowballPDESolver",
    "PhoenixPDESolver",
    "LocalVolPDESolver",
    "HestonPDESolver",
    "HestonSLVPDESolver",
    "LocalVolSnowballPDESolver",
    "HestonSnowballPDESolver",
    "HestonSLVSnowballPDESolver",
    "LocalVolPhoenixPDESolver",
    "HestonPhoenixPDESolver",
    "HestonSLVPhoenixPDESolver",
    # Grid utilities
    # Quadrature
    "EuropeanQuadEngine",
    "BarrierQuadEngine",
    "OneTouchQuadEngine",
    "SnowballQuadEngine",
    "KOResetSnowballQuadEngine",
    "PhoenixQuadEngine",
]
