"""
SIMM Calibration Data Module.

This package provides all calibration parameters for ISDA SIMM v2.6
(effective December 2, 2023), transcribed table-by-table from the
methodology document (quantark/simm/doc/isda_simm.md):

- Section D: Interest Rate risk (ir)
- Section E: Credit Qualifying risk (credit_qualifying)
- Section F: Credit Non-Qualifying risk (credit_non_qualifying)
- Section G: Equity risk (equity)
- Section H: Commodity risk (commodity)
- Section I: Foreign Exchange risk (fx)
- Section J: Concentration thresholds (within each risk-class module)
- Section K: Correlation between risk classes (cross_risk)
"""

from quantark.simm.calibration.version import CURRENT_VERSION

from quantark.simm.calibration.ir import (
    IR_DELTA_RISK_WEIGHTS,
    IR_INFLATION_RISK_WEIGHT,
    IR_XCCY_BASIS_RISK_WEIGHT,
    IR_HVR,
    IR_VRW,
    IR_TENOR_CORRELATIONS,
    IR_TENOR_INDEX,
    IR_SUB_CURVE_CORRELATION,
    IR_INFLATION_CORRELATION,
    IR_XCCY_BASIS_CORRELATION,
    IR_INTER_CURRENCY_CORRELATION,
    IR_DELTA_CONCENTRATION_THRESHOLDS,
    IR_VEGA_CONCENTRATION_THRESHOLDS,
)
from quantark.simm.calibration.credit_qualifying import (
    CREDIT_QUALIFYING_RISK_WEIGHTS,
    CREDIT_QUALIFYING_VRW,
    CREDIT_QUALIFYING_BASE_CORRELATION_RISK_WEIGHT,
    CREDIT_QUALIFYING_BASE_CORRELATION_INTER_INDEX_CORRELATION,
    CREDIT_QUALIFYING_SAME_ISSUER_CORRELATION,
    CREDIT_QUALIFYING_DIFFERENT_ISSUER_CORRELATION,
    CREDIT_QUALIFYING_RESIDUAL_SAME_ISSUER_CORRELATION,
    CREDIT_QUALIFYING_RESIDUAL_DIFFERENT_ISSUER_CORRELATION,
    CREDIT_QUALIFYING_INTER_BUCKET_CORRELATIONS,
    CREDIT_QUALIFYING_DELTA_CONCENTRATION_THRESHOLDS,
    CREDIT_QUALIFYING_VEGA_CONCENTRATION_THRESHOLD,
)
from quantark.simm.calibration.credit_non_qualifying import (
    CREDIT_NON_QUALIFYING_RISK_WEIGHTS,
    CREDIT_NON_QUALIFYING_VRW,
    CREDIT_NON_QUALIFYING_SAME_GROUP_CORRELATION,
    CREDIT_NON_QUALIFYING_DIFFERENT_GROUP_CORRELATION,
    CREDIT_NON_QUALIFYING_RESIDUAL_SAME_GROUP_CORRELATION,
    CREDIT_NON_QUALIFYING_RESIDUAL_DIFFERENT_GROUP_CORRELATION,
    CREDIT_NON_QUALIFYING_INTER_BUCKET_CORRELATION,
    CREDIT_NON_QUALIFYING_DELTA_CONCENTRATION_THRESHOLDS,
    CREDIT_NON_QUALIFYING_VEGA_CONCENTRATION_THRESHOLD,
)
from quantark.simm.calibration.equity import (
    EQUITY_RISK_WEIGHTS,
    EQUITY_HVR,
    EQUITY_VRW_DEFAULT,
    EQUITY_VRW_VOLATILITY_INDEX,
    get_equity_vrw,
    EQUITY_INTRA_BUCKET_CORRELATIONS,
    EQUITY_INTER_BUCKET_CORRELATIONS,
    EQUITY_DELTA_CONCENTRATION_THRESHOLDS,
    EQUITY_VEGA_CONCENTRATION_THRESHOLDS,
)
from quantark.simm.calibration.commodity import (
    COMMODITY_RISK_WEIGHTS,
    COMMODITY_HVR,
    COMMODITY_VRW,
    COMMODITY_INTRA_BUCKET_CORRELATIONS,
    COMMODITY_INTER_BUCKET_CORRELATIONS,
    COMMODITY_DELTA_CONCENTRATION_THRESHOLDS,
    COMMODITY_VEGA_CONCENTRATION_THRESHOLDS,
)
from quantark.simm.calibration.fx import (
    FX_RISK_WEIGHTS,
    FX_HVR,
    FX_VRW,
    FX_DELTA_CORRELATIONS,
    FX_VEGA_CORRELATION,
    FX_DELTA_CONCENTRATION_THRESHOLDS,
    FX_VEGA_CONCENTRATION_THRESHOLDS,
    get_fx_vega_concentration_threshold,
)
from quantark.simm.calibration.cross_risk import (
    INTER_RISK_CLASS_CORRELATIONS,
    INTER_RISK_CLASS_CORRELATION_LABELS,
)
from quantark.simm.calibration.accessors import (
    RISK_CLASS_ORDER,
    PHI_INV_99,
    PHI_INV_995,
    VOL_SCALE,
    get_inter_risk_class_correlation,
    scaling_function,
)

__all__ = [
    "CURRENT_VERSION",
    # IR (Section D, J.1, J.6)
    "IR_DELTA_RISK_WEIGHTS",
    "IR_INFLATION_RISK_WEIGHT",
    "IR_XCCY_BASIS_RISK_WEIGHT",
    "IR_HVR",
    "IR_VRW",
    "IR_TENOR_CORRELATIONS",
    "IR_TENOR_INDEX",
    "IR_SUB_CURVE_CORRELATION",
    "IR_INFLATION_CORRELATION",
    "IR_XCCY_BASIS_CORRELATION",
    "IR_INTER_CURRENCY_CORRELATION",
    "IR_DELTA_CONCENTRATION_THRESHOLDS",
    "IR_VEGA_CONCENTRATION_THRESHOLDS",
    # Credit Qualifying (Section E, J.2, J.7)
    "CREDIT_QUALIFYING_RISK_WEIGHTS",
    "CREDIT_QUALIFYING_VRW",
    "CREDIT_QUALIFYING_BASE_CORRELATION_RISK_WEIGHT",
    "CREDIT_QUALIFYING_BASE_CORRELATION_INTER_INDEX_CORRELATION",
    "CREDIT_QUALIFYING_SAME_ISSUER_CORRELATION",
    "CREDIT_QUALIFYING_DIFFERENT_ISSUER_CORRELATION",
    "CREDIT_QUALIFYING_RESIDUAL_SAME_ISSUER_CORRELATION",
    "CREDIT_QUALIFYING_RESIDUAL_DIFFERENT_ISSUER_CORRELATION",
    "CREDIT_QUALIFYING_INTER_BUCKET_CORRELATIONS",
    "CREDIT_QUALIFYING_DELTA_CONCENTRATION_THRESHOLDS",
    "CREDIT_QUALIFYING_VEGA_CONCENTRATION_THRESHOLD",
    # Credit Non-Qualifying (Section F, J.2, J.7)
    "CREDIT_NON_QUALIFYING_RISK_WEIGHTS",
    "CREDIT_NON_QUALIFYING_VRW",
    "CREDIT_NON_QUALIFYING_SAME_GROUP_CORRELATION",
    "CREDIT_NON_QUALIFYING_DIFFERENT_GROUP_CORRELATION",
    "CREDIT_NON_QUALIFYING_RESIDUAL_SAME_GROUP_CORRELATION",
    "CREDIT_NON_QUALIFYING_RESIDUAL_DIFFERENT_GROUP_CORRELATION",
    "CREDIT_NON_QUALIFYING_INTER_BUCKET_CORRELATION",
    "CREDIT_NON_QUALIFYING_DELTA_CONCENTRATION_THRESHOLDS",
    "CREDIT_NON_QUALIFYING_VEGA_CONCENTRATION_THRESHOLD",
    # Equity (Section G, J.3, J.8)
    "EQUITY_RISK_WEIGHTS",
    "EQUITY_HVR",
    "EQUITY_VRW_DEFAULT",
    "EQUITY_VRW_VOLATILITY_INDEX",
    "get_equity_vrw",
    "EQUITY_INTRA_BUCKET_CORRELATIONS",
    "EQUITY_INTER_BUCKET_CORRELATIONS",
    "EQUITY_DELTA_CONCENTRATION_THRESHOLDS",
    "EQUITY_VEGA_CONCENTRATION_THRESHOLDS",
    # Commodity (Section H, J.4, J.9)
    "COMMODITY_RISK_WEIGHTS",
    "COMMODITY_HVR",
    "COMMODITY_VRW",
    "COMMODITY_INTRA_BUCKET_CORRELATIONS",
    "COMMODITY_INTER_BUCKET_CORRELATIONS",
    "COMMODITY_DELTA_CONCENTRATION_THRESHOLDS",
    "COMMODITY_VEGA_CONCENTRATION_THRESHOLDS",
    # FX (Section I, J.5, J.10)
    "FX_RISK_WEIGHTS",
    "FX_HVR",
    "FX_VRW",
    "FX_DELTA_CORRELATIONS",
    "FX_VEGA_CORRELATION",
    "FX_DELTA_CONCENTRATION_THRESHOLDS",
    "FX_VEGA_CONCENTRATION_THRESHOLDS",
    "get_fx_vega_concentration_threshold",
    # Cross-risk-class (Section K)
    "INTER_RISK_CLASS_CORRELATIONS",
    "INTER_RISK_CLASS_CORRELATION_LABELS",
    # Shared accessors
    "RISK_CLASS_ORDER",
    "PHI_INV_99",
    "PHI_INV_995",
    "VOL_SCALE",
    "get_inter_risk_class_correlation",
    "scaling_function",
]
