"""HTML report generation for stress test results."""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional, Union

import pandas as pd

from stresstest.equity.report.visualizer import StressTestVisualizer
from stresstest.equity.results import StressTestResults
from stresstest.results.result_aggregator import ResultAggregator


class ReportGenerator:
    """
    Generates comprehensive HTML reports for stress test results.
    """

    def __init__(self) -> None:
        self.visualizer = StressTestVisualizer()

    def generate_report(
        self,
        results: StressTestResults,
        output_path: Union[str, Path],
        title: Optional[str] = None,
        include_plots: bool = True,
    ) -> None:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        if title is None:
            title = f"Stress Test Report - {results.execution_timestamp.strftime('%Y-%m-%d %H:%M')}"

        html = self._generate_html(results, title, include_plots)
        with open(output_path, "w", encoding="utf-8") as handle:
            handle.write(html)

        print(f"Generated HTML report: {output_path}")

    def _generate_html(
        self,
        results: StressTestResults,
        title: str,
        include_plots: bool,
    ) -> str:
        risk_summary = ResultAggregator.get_risk_summary(results)
        summary_df = results.to_summary_dataframe()

        fi_section = self._generate_fi_metrics_section(results)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{title}</h1>
            <p class="timestamp">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </header>

        {self._generate_executive_summary(results, risk_summary)}
        {self._generate_scenario_results(results, summary_df)}
        {self._generate_risk_metrics(risk_summary)}
        {fi_section}

        {self._generate_plots_section(results) if include_plots else ''}

        {self._generate_detailed_scenarios(results)}

        <footer>
            <p>Generated by QuantArk Stress Test Module</p>
        </footer>
    </div>
</body>
</html>"""

    def _get_css(self) -> str:
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f4f4f4;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }

        header {
            text-align: center;
            padding: 20px 0;
            border-bottom: 3px solid #2c3e50;
            margin-bottom: 30px;
        }

        h1 {
            color: #2c3e50;
            margin-bottom: 10px;
        }

        h2 {
            color: #34495e;
            margin-top: 30px;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #ecf0f1;
        }

        h3 {
            color: #34495e;
            margin-top: 20px;
            margin-bottom: 10px;
        }

        .timestamp {
            color: #7f8c8d;
            font-style: italic;
        }

        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }

        .summary-card {
            background-color: #ecf0f1;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid #3498db;
        }

        .summary-card.negative {
            border-left-color: #e74c3c;
        }

        .summary-card.positive {
            border-left-color: #2ecc71;
        }

        .summary-card h3 {
            margin-top: 0;
            font-size: 0.9em;
            text-transform: uppercase;
            color: #7f8c8d;
        }

        .summary-card .value {
            font-size: 1.8em;
            font-weight: bold;
            color: #2c3e50;
        }

        .summary-card .value.negative {
            color: #e74c3c;
        }

        .summary-card .value.positive {
            color: #2ecc71;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background-color: white;
        }

        th {
            background-color: #34495e;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: 600;
        }

        td {
            padding: 10px 12px;
            border-bottom: 1px solid #ecf0f1;
        }

        tr:hover {
            background-color: #f8f9fa;
        }

        .positive {
            color: #2ecc71;
        }

        .negative {
            color: #e74c3c;
        }

        .neutral {
            color: #7f8c8d;
        }

        .plot-container {
            margin: 30px 0;
            text-align: center;
        }

        .plot-container img {
            max-width: 100%;
            height: auto;
            border: 1px solid #ecf0f1;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .scenario-detail {
            background-color: #f8f9fa;
            padding: 15px;
            margin: 15px 0;
            border-radius: 8px;
            border-left: 4px solid #3498db;
        }

        .stress-list {
            list-style-type: none;
            padding-left: 20px;
        }

        .stress-list li {
            padding: 5px 0;
        }

        footer {
            text-align: center;
            padding: 20px 0;
            margin-top: 40px;
            border-top: 2px solid #ecf0f1;
            color: #7f8c8d;
            font-size: 0.9em;
        }
        """

    def _generate_executive_summary(
        self,
        results: StressTestResults,
        risk_summary: Dict[str, Any],
    ) -> str:
        worst = results.get_worst_scenario()
        best = results.get_best_scenario()

        return f"""
        <section class="executive-summary">
            <h2>Executive Summary</h2>
            <div class="summary-grid">
                <div class="summary-card">
                    <h3>Baseline Portfolio Value</h3>
                    <div class="value">${results.baseline_value:,.2f}</div>
                </div>
                <div class="summary-card">
                    <h3>Scenarios Tested</h3>
                    <div class="value">{len(results.scenario_results)}</div>
                </div>
                <div class="summary-card negative">
                    <h3>Worst Case</h3>
                    <div class="value negative">${worst.portfolio_pnl:,.2f}</div>
                    <p style="font-size: 0.9em; margin-top: 5px;">{worst.scenario.name} ({worst.portfolio_pnl_pct:+.2f}%)</p>
                </div>
                <div class="summary-card positive">
                    <h3>Best Case</h3>
                    <div class="value positive">${best.portfolio_pnl:,.2f}</div>
                    <p style="font-size: 0.9em; margin-top: 5px;">{best.scenario.name} ({best.portfolio_pnl_pct:+.2f}%)</p>
                </div>
            </div>
        </section>
        """

    def _generate_scenario_results(
        self,
        results: StressTestResults,
        summary_df: pd.DataFrame,
    ) -> str:
        html = """
        <section class="scenario-results">
            <h2>Scenario Results</h2>
            <table>
                <thead>
                    <tr>
                        <th>Scenario</th>
                        <th>Description</th>
                        <th>Portfolio Value</th>
                        <th>P&L</th>
                        <th>P&L %</th>
                    </tr>
                </thead>
                <tbody>
        """

        for _, row in summary_df.iterrows():
            pnl_class = "positive" if row["portfolio_pnl"] >= 0 else "negative"
            if row["scenario_name"] == "Baseline":
                pnl_class = "neutral"

            html += f"""
                    <tr>
                        <td><strong>{row['scenario_name']}</strong></td>
                        <td>{row.get('scenario_description', '')}</td>
                        <td>${row['portfolio_value']:,.2f}</td>
                        <td class="{pnl_class}">${row['portfolio_pnl']:,.2f}</td>
                        <td class="{pnl_class}">{row['portfolio_pnl_pct']:+.2f}%</td>
                    </tr>
            """

        html += """
                </tbody>
            </table>
        </section>
        """

        return html

    def _generate_risk_metrics(self, risk_summary: Dict[str, Any]) -> str:
        return f"""
        <section class="risk-metrics">
            <h2>Risk Metrics</h2>
            <div class="summary-grid">
                <div class="summary-card">
                    <h3>Average P&L</h3>
                    <div class="value">${risk_summary['avg_pnl']:,.2f}</div>
                    <p style="font-size: 0.9em; margin-top: 5px;">({risk_summary['avg_pnl_pct']:+.2f}%)</p>
                </div>
                <div class="summary-card">
                    <h3>Median P&L</h3>
                    <div class="value">${risk_summary['median_pnl']:,.2f}</div>
                    <p style="font-size: 0.9em; margin-top: 5px;">({risk_summary['median_pnl_pct']:+.2f}%)</p>
                </div>
                <div class="summary-card negative">
                    <h3>Max Drawdown</h3>
                    <div class="value negative">{risk_summary['max_drawdown_pct']:.2f}%</div>
                </div>
                <div class="summary-card positive">
                    <h3>Max Upside</h3>
                    <div class="value positive">{risk_summary['max_upside_pct']:+.2f}%</div>
                </div>
            </div>
        </section>
        """

    def _generate_fi_metrics_section(self, results: StressTestResults) -> str:
        get_series = getattr(results, "get_dv01_series", None)
        if not callable(get_series):
            return ""

        dv01_df = get_series()
        if dv01_df is None or dv01_df.empty:
            return ""

        table_html = dv01_df.to_html(index=False, float_format=lambda x: f"{x:,.4f}")
        return f"""
        <section class="fi-metrics">
            <h2>Fixed Income Metrics</h2>
            <p>DV01 / Convexity / Carry per scenario.</p>
            {table_html}
        </section>
        """

    def _generate_plots_section(self, results: StressTestResults) -> str:
        return """
        <section class="visualizations">
            <h2>Visualizations</h2>
            <p><em>For detailed visualizations, please use the interactive dashboard or export plots separately.</em></p>
        </section>
        """

    def _generate_detailed_scenarios(self, results: StressTestResults) -> str:
        html = """
        <section class="detailed-scenarios">
            <h2>Detailed Scenario Breakdown</h2>
        """

        for result in results.scenario_results:
            pnl_class = "positive" if result.portfolio_pnl >= 0 else "negative"
            html += f"""
            <div class="scenario-detail">
                <h3>{result.scenario.name}</h3>
                <p><strong>Description:</strong> {result.scenario.description or 'N/A'}</p>
                <p><strong>P&L:</strong> <span class="{pnl_class}">${result.portfolio_pnl:,.2f} ({result.portfolio_pnl_pct:+.2f}%)</span></p>
                <p><strong>Portfolio Value:</strong> ${result.portfolio_value:,.2f}</p>

                <h4>Stresses Applied:</h4>
                <ul class="stress-list">
            """

            for stress in result.scenario.stresses:
                html += f"""
                    <li>• {stress.parameter}: {stress.stress_type.value} {stress.stress_value:+.2%} at {stress.level.value} level</li>
                """

            html += """
                </ul>
            </div>
            """

        html += """
        </section>
        """

        return html

