"""Capability-matrix renderer over the checked-in engine inventory (spec §21).

Renders ``docs/execution/capability-matrix.md`` from ``ENGINE_INVENTORY``.
Like the inventory itself, this module performs no asset imports and no I/O at
import time; the output is deterministic (no timestamps) so CI can enforce
freshness by exact string comparison:

    python -m quantark.execution.capability_matrix docs/execution/capability-matrix.md
"""
from collections import Counter

from quantark.execution.inventory import ENGINE_INVENTORY

__all__ = ["render_capability_matrix"]

_HEADER = """\
# QuantArk execution framework — engine capability matrix

> GENERATED by `python -m quantark.execution.capability_matrix` from
> `quantark.execution.inventory.ENGINE_INVENTORY` — do not edit by hand.
> CI enforces freshness (`test/execution/test_capability_matrix.py`).

The inventory is the release-gate source of truth (spec §18). States:
`supported` (native session adapter), `temporary_legacy` (session-reachable
through the serial legacy adapter; PV-only guarantee), `not_applicable`
(with rationale), and per-capability `*_capable` states for batch, adaptive
RQMC, and prepared-artifact execution.
"""

_SESSION_NOTE = """\
## Session-level capabilities

Scenario, process, and Dask execution are SESSION-level capabilities
(`PricingSession.run_scenarios` plus registered transformer/runner/factory
ids), not per-engine ones — any engine an adapter or runner can drive
participates. The inventory therefore carries no per-engine scenario column;
the scenario exit gates live in `test/execution/test_scenario_*`,
`test_worker_spec`, `test_processes_backend`, `test_dask_backend`, and
`test_surface_shock_scenarios`.
"""

_GROUP_TITLES = {
    ("equity", "mc"): "Equity Monte Carlo",
    ("equity", "pde"): "Equity PDE",
    ("fx", "mc"): "FX Monte Carlo",
    ("fx", "pde"): "FX PDE",
    ("credit", "mc"): "Credit Monte Carlo",
    ("bond", "pde"): "Bond PDE",
}


def _summary_lines() -> list:
    lines = ["## Summary", ""]
    lines.append(f"Exported engines inventoried: **{len(ENGINE_INVENTORY)}**")
    lines.append("")
    for field, title in (
        ("adoption_state", "Adoption"),
        ("batch_state", "Batch"),
        ("adaptive_state", "Adaptive RQMC"),
        ("prepared_state", "Prepared artifacts"),
    ):
        counts = Counter(getattr(r, field) for r in ENGINE_INVENTORY)
        rendered = ", ".join(
            f"`{state}`: {count}" for state, count in sorted(counts.items())
        )
        lines.append(f"- **{title}** — {rendered}")
    lines.append("")
    return lines


def _cell(state: str, rationale, footnotes: dict) -> str:
    if not rationale:
        return f"`{state}`"
    note_id = footnotes.setdefault(rationale, len(footnotes) + 1)
    return f"`{state}` ({note_id})"


def render_capability_matrix() -> str:
    lines = [_HEADER]
    lines.extend(_summary_lines())

    groups = {}
    for record in ENGINE_INVENTORY:
        groups.setdefault(
            (record.asset_family, record.engine_type), []
        ).append(record)

    footnotes: dict = {}
    for key, records in groups.items():
        title = _GROUP_TITLES.get(key, f"{key[0]} {key[1]}")
        lines.append(f"## {title} ({len(records)} engines)")
        lines.append("")
        lines.append(
            "| Engine | Model | Products | Planning | Role | Adoption "
            "| Batch | Adaptive | Prepared | Validation profile |"
        )
        lines.append("|---|---|---|---|---|---|---|---|---|---|")
        for r in records:
            lines.append(
                "| `{name}` | {model} | {product} | {planning} | {role} "
                "| {adoption} | {batch} | {adaptive} | {prepared} "
                "| {profile} |".format(
                    name=r.name,
                    model=r.model_family,
                    product=r.product_family,
                    planning=r.planning,
                    role=r.role,
                    adoption=_cell(r.adoption_state, r.reason, footnotes),
                    batch=_cell(r.batch_state, r.batch_rationale, footnotes),
                    adaptive=_cell(
                        r.adaptive_state, r.adaptive_rationale, footnotes
                    ),
                    prepared=_cell(
                        r.prepared_state, r.prepared_rationale, footnotes
                    ),
                    profile=(
                        f"`{r.validation_profile}`"
                        if r.validation_profile
                        else "—"
                    ),
                )
            )
        lines.append("")

    lines.append("## Rationale notes")
    lines.append("")
    for text, note_id in sorted(footnotes.items(), key=lambda kv: kv[1]):
        lines.append(f"{note_id}. {text}")
    lines.append("")
    lines.append(_SESSION_NOTE)
    return "\n".join(lines)


def main(argv) -> None:
    text = render_capability_matrix()
    if argv:
        import pathlib

        path = pathlib.Path(argv[0])
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")
    else:
        print(text, end="")


if __name__ == "__main__":
    import sys

    main(sys.argv[1:])
